application: pyxer
version: 1
runtime: python
api_version: 1

handlers:
#- url: /res/.*
#  script: $PYTHON_LIB/google/appengine/ext/zipserve
- url: /docs/(.*)
  static_files: docs/\1
  upload: docs/(.*)                                    
- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico  
- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt  
- url: .*
  script: paste-deploy.py

skip_files: |
 ^(
 ((utils|bin|cache|tests|include|Scripts|tmp)/.*)|
 (.*/)?(
 (.*\.exe)|
 (.*\.bat)|
 (.*\.pyd)|
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 ([Ll]ib/encodings/.*)|
 (Lib/[^/]+\.py)|
 ([Ll]ib/.+?/[Ww]eb[Oo]b-.+?\.egg/.*)|
 (\..*)|
 ))$
