application: pyxer
version: 1
runtime: python
api_version: 1

handlers:
#- url: /res/.*
#  script: $PYTHON_LIB/google/appengine/ext/zipserve
- url: .*
  script: paste-deploy.py

skip_files: |
 ^(.*/)?(
 (.*\.exe)|
 (.*\.bat)|
 (.*\.pyd)|
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (Scripts/.*)|
 (bin/.*)|
 ([Ll]ib/encodings/.*)|
 (Lib/[^/]+\.py)|
 ([Ll]ib/.+?/webob-.+?\.egg/.*)|
 (cache/.*)|
 (tests/.*)|
 (include/.*)|
 (\..*)|
 )$
