application: pyxer
version: 1
runtime: python
api_version: 1

handlers:
- url: .*
  script: paste-deploy.py

#skip_files: |
# ^bin/.*$|
# ^lib/python2.5/[^/]+$|
# ^(.*/)?(
# (app\.yaml)|
# (app\.yml)|
# (index\.yaml)|
# (index\.yml)|
# (#.*#)|
# (.*~)|
# (.*\.py[co])|
# (.*/RCS/.*)|
# (\..*)|
# )$
